Repository Burnout-Devil/HacktoberFest-DSA2022, pull requests merged in 2022-10, with the labels that each got.

#44 Created code to implement stack using list in python
  OperationOfStack.py
Labels: Hacktoberfest, hacktoberfest accepted

#41 Created code for diamond pattern in Python
  DiamondPattern.py
Labels: Hacktoberfest, hacktoberfest accepted

#42 Created code to implement BST in Python
  ImplementBST.py
Labels: Hacktoberfest, hacktoberfest accepted

#49 Created calculator in java
  Calculator.java
Labels: hacktoberfest accepted

#67 Singly Linked List with user input
  SinglyLinkedList.c
Labels: hacktoberfest accepted

#69 issue #68
  linkedlist_concatenation.c
Labels: hacktoberfest accepted

#79 Create Circular_Singly_LinkedList.c
  Circular_Singly_LinkedList.c
Labels: hacktoberfest accepted

#84 Create Balanced_Paranthesis.c
  Balanced_Paranthesis.c
Labels: hacktoberfest accepted

#88 added circular queue
  CircularQueue.java
Labels: hacktoberfest accepted

#94 Created Reverse Path in Java
  reversepath.java
Labels: hacktoberfest accepted

#97 valid Parenthesis in Java
  validParenthesis.java
Labels: hacktoberfest accepted, hacktoberfest-2022

#115 Create Operation of Queue.c
  Operation of Queue.c
Labels: hacktoberfest accepted

#109 feat : Added running sum
  running_sum.cpp
Labels: hacktoberfest accepted
